services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "s434780@gmail.com"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "1991801122"
      - key: WEBHOOK_TUNNEL_URL
        value: "https://n8n-yaqh.onrender.com"
